language: android
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-18  ANDROID_ABI=armeabi-v7a

before_install:
  - echo $TRAVIS_BUILD_DIR
  - cd TravisCITestApp

android:
  components:
    - tools
    - platform-tools
    - build-tools-21.0.2
    - android-21
    - android-19
    - android-18
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-19
    - sys-img-armeabi-v7a-android-18
    - extra-android-m2repository
    - extra-android-support

before_script:
  - echo $TRAVIS_BUILD_DIR
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script:
  - echo $TRAVIS_BUILD_DIR
  - ./gradlew connectedAndroidTest
